name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    with:
      python-version: '3.8'
      architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint
    - name: Lint with flake8
      run: |
        pylint *.py
    # - name: Test with pytest
    #   run: |
    #     pip install pytest
    #     pytest
